### ISSUE TITLE
Cambiamento Sprint Backlog

### ISSUE THREAD

**Issue by pubbiali** [MatteoCazzaniga/IngegneriaSoftware_22-23#3]
Aggiornamento documentazione Sprint Backlog.

**Comment by MatteoCazzaniga** [comment]
Ho aggiornato correttamente gli Sprint Backlog utilizzati con i Projects di GitHub, provate a controllarne la correttezza

**Comment by pubbiali** [comment]
Ho visto il project "Documentation" in cui nella sezione "Delete" è presente il diagramma dei package.
Questo significa che il diagramma UML dei package che attualmente è presente nella cartella Diagrammi è da eliminare da quella cartella?
