### ISSUE TITLE
Test JUnit

### ISSUE THREAD

**Issue by MatteoCazzaniga** [MatteoCazzaniga/IngegneriaSoftware_22-23#5]
Proviamo a controllare che i test effettuati con Junit vengano caricati e lavorino nel modo corretto

**Comment by bottuz** [comment]
Test funzionanti, l'unico che crea un pò di problemi è quello della classe TransazioneTest, perchè la data/ora differisce di qualche secondo dall'expected, ma non crea in nessun modo errore!
